name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-18.04
    steps:
      - name: Build Android
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: build
